[package]
name = "sturgeon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
num = "0.4.3"
once_cell = "1.18.0"
rand = "0.8.5"
thiserror = "2.0.11"